modLoader="javafml"
loaderVersion="[2.0.0,)"
license="MIT"

[[mods]]
modId="uchiha"
version="1.0.0"
displayName="Uchiha Clan"
authors="LonelyLol11"
description='''Sharingan clan powers and abilities mod for Minecraft'''

[[dependencies.uchiha]]
modId="neoforge"
type="required"
versionRange="[21.1.213,)"
ordering="NONE"
side="BOTH"

[[dependencies.uchiha]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
